/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crocodile;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean subElement(ArrayList<Integer> arr1, ArrayList<Integer> arr2, ArrayList<Integer> arr3, int e ) { 

        if(arr1 == null || arr2 == null || arr3 == null) 
            return false;

        if (arr1.contains(e) && arr2.contains(e) && arr3.contains(e)) 
            return true;
        
        return false;
    }
}
