/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crocodile;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void test() {
        ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList(3,9,18,27,36));
        ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(12,18,30,34,36));
        ArrayList<Integer> arr3 = new ArrayList<>(Arrays.asList(9,18,27,30,32,36));
      assertTrue(App.subElement(arr1,arr2,arr3,36));  

    }

    @Test
    public void testNotFound() {
        ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList(3,9,18,27,36));
        ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(12,18,30,34,36));
        ArrayList<Integer> arr3 = new ArrayList<>(Arrays.asList(9,18,27,30,32,36));
        assertFalse(App.subElement(arr1,arr2,arr3,21));  

    }

    @Test
    public void testEmptyArrays() {
        ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList());
        ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(12,18,30,34,36));
        ArrayList<Integer> arr3 = new ArrayList<>(Arrays.asList(9,18,27,30,32,36));
        assertFalse(App.subElement(arr1, arr2, arr3, 36));

    }

    @Test
    public void testNullArray() {

        ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList(3,9,18,27,36));
        ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(12,18,30,34,36));
     
        assertFalse(App.subElement(arr1, arr2, null, 36));

    }

    @Test
    public void testNullEmptyArrays() {

        ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList());
        ArrayList<Integer> arr3 = new ArrayList<>(Arrays.asList(9,18,27,30,32,36));

        assertFalse(App.subElement(arr1, null, arr3, 36));
       
    }





}
